apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: swigy-frontend
  labels:
    app: swigy-frontend
spec:
  serviceName: swigy-frontend-service
  replicas: 1
  selector:
    matchLabels:
      app: swigy-frontend
  template:
    metadata:
      labels:
        app: swigy-frontend
    spec:
      terminationGracePeriodSeconds: 30
      tolerations:                            # <--- Add this
        - key: "eks.amazonaws.com/compute-type"
          operator: "Equal"
          value: "fargate"
          effect: "NoSchedule"
      containers:
        - name: swigy-frontend
          image: manoj3003/swigy:4
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 250m
              memory: 1024Mi
          volumeMounts:
            - name: volume1
              mountPath: /opt/backend
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: volume1
          persistentVolumeClaim:
            claimName: efs-pvc
